# Generated by Django 5.2.3 on 2025-06-25 07:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_developers', models.IntegerField(blank=True, null=True)),
                ('time_estimate', models.CharField(blank=True, max_length=64, null=True)),
                ('cost_estimate', models.CharField(blank=True, max_length=64, null=True)),
                ('services', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_info', to='chat_bot.chatsession')),
            ],
        ),
    ]
