# Generated by Django 5.2.3 on 2025-06-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot', '0002_projectinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='memory_buffer',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
